name: Release Module

on:
  push:
    branches:
      - main

jobs:
  fmt:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-fmt.yml@main
  release:
    uses: diegotony/gh-pipelines/.github/workflows/sn-release.yml@main
