name: Release Module

on:
  push:
    branches:
      - main

jobs:
  fmt:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-fmt.yml@main
  docs:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-tfdocs.yml@main
  release:
    needs: fmt
    uses: diegotony/gh-pipelines/.github/workflows/sm-release.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}